<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>GuardEscapePlugin</AssemblyName>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>../Libraries/Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="Mirror">
      <HintPath>../Libraries/Mirror.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../Libraries/UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>../Libraries/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
