<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <!-- Unity / 游戏 DLL（你解压的 Libraries.zip） -->
    <Reference Include="UnityEngine">
      <HintPath>libs/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>libs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Mirror">
      <HintPath>libs/Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
