
name: Build SCP Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet (safe)
      run: nuget restore src/GuardEscapeToMTF.csproj

    - name: Build plugin
      run: msbuild src/GuardEscapeToMTF.csproj /p:Configuration=Release

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: GuardEscapeToMTF
        path: src/bin/Release/net472/*.dll
